### Numpy EXPLORATION

Homogeneus multidimensional array . Table of elements all of the same type .
Numpy dimensions are called axis . An array of [1,2,3] has one axis and a lenght of three
The module is called numpy. Powerfull data structure for efficient computation of arrays and matrices .

In [1]:
import numpy as np

#### Create an array 

Elements must be a multiple of the dimensions .
a = random matrix with a given dimension .
b = designed array adoc
np.array([])

In [2]:
elements = 6 
rows = 2 #->filas
columns = 3 #->columnas
##RANDOM
c = np.random.random((rows, columns))
##ORDERED MATRIX
a = np.arange(elements).reshape(rows, columns) ### <--- ORDERED matrix
##ONES . Can specify data type 
ones = np.ones((rows, columns))
##ZEROS. Can specify data type 
np.zeros((rows,columns), dtype=np.int16)
##EMPTY
np.empty((rows,columns))
##IDENTITY
np.identity(rows)
## CREATE AN ARRAY OF EVENLY-SPACED VALUES <-- array de elementos con un intervalo.
# En éste caso del 0 al 2 con 6 elementos 
np.linspace(0,2,elements)


array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [3]:
b = np.array([[1,2,3], [3,2,1]])
b 

array([[1, 2, 3],
       [3, 2, 1]])

#### Inspection

In [4]:
# TYPE OF ELEMENTS
a.dtype
# NUMBER OF DIMENSIONS
a.ndim 
# NUMBER OF ELEMENTS 
a.size
# MEMORY LAYOUT
a.flags
# LENGTH OF ONE ARRAY ELEMENT in BYTES
a.itemsize
# PRINT LENGTH
print(len(a))
#CHANGE DATA TYPE 
a.astype(float)

2


array([[0., 1., 2.],
       [3., 4., 5.]])

#### Convert a list into an array 

In [5]:
list = [4, 3, 2, 1, 1, 1]
np.array(list)

array([4, 3, 2, 1, 1, 1])

#### Convert string into array 

The conversion must be : split the string and convert it into array 

In [6]:
text = 'a,b,c'
text_array = np.array(text.split('.'))
text_array

array(['a,b,c'], dtype='<U5')

#### Operations with single array 

In [7]:
c.sum() #<--- sum of elements 

4.025986519384643

In [17]:
c.min() #<--- min of elements

0.1166811342064743

In [18]:
c.max() #<--- max of elements

0.9528305621136551

#### Operations

Dimensions must be compatible 

In [8]:
np.add(a,b) #<-- a + b

array([[1, 3, 5],
       [6, 6, 6]])

In [9]:
np.multiply(a,b) #<-- a*b

array([[0, 2, 6],
       [9, 8, 5]])

In [11]:
np.subtract(a,b) #<-- a - b 

array([[-1, -1, -1],
       [ 0,  2,  4]])

In [12]:
np.divide(a,b)

array([[0.        , 0.5       , 0.66666667],
       [1.        , 2.        , 5.        ]])

In [13]:
np.remainder(a,b) ##<-- el resto ? 

array([[0, 1, 2],
       [0, 0, 0]])

In [14]:
b2 = np.arange(9).reshape(3,3) # <-- 2x3 3x3 producto vectorial 
np.dot(a,b2)

array([[15, 18, 21],
       [42, 54, 66]])

In [15]:
a.cumsum(axis=1) ## <-- suma acumulada en el ultimo de la lista

array([[ 0,  1,  3],
       [ 3,  7, 12]])

In [16]:
a.mean() # <--- mean
np.corrcoef(a) # <--- correlation coef
np.std(a) # <--- standar deviation 

1.707825127659933

#### Logical Operators

In [ ]:
np.logical_and(a,b)

In [ ]:
np.logical_or(a,b)

In [ ]:
np.logical_not(a,b)

In [ ]:
np.array_equal(a,b)

#### Subset, Slice, and Index Arrays 

Operations that takes a part of the original array to use in further analysis or other operations. 
Use [] as the index operators 
pass intergers to these square brackets 

##### Subsetting ---> LOCATIONS

In [19]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
a[1] ## ---> select second row

array([3, 4, 5])

In [21]:
a[1][0] # ---> select second row first element 

3

##### Slicing ---> REGIONS

In essence , This is great for selecting regions inside numpy and regions with conditions
it works bassically 
a[start:end] 
a[start:]
a[:end]

In [24]:
a[0:1] # ---> select first row

array([[0, 1, 2]])

In [25]:
a[0:2,1] # ---> select the same item (1) from rows 0 and 1 
a[:,1] # ---> all the rows from the second column

array([1, 4])

In [26]:
a[1,...]

array([3, 4, 5])

##### Indexing <--- BOLEAN INDEXING 

Instead of selecting elements, rows or columns based on index number, select values from array that fulfill a certain condition . It returns an array 
You can build it by a[my_condition] and use operators for define that 

In [28]:
a[a<2]

array([0, 1])

In [35]:
bigger_than_3 = (a >= 3 | a == 3)
bigger_and_equal_than_3 = (a >=3 & a==3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [30]:
a[bigger_than_3]

array([3, 4, 5])